-- Creates table for blogful app.
-- TIMESTAMPTZ type which is shorthand for TIMESTAMP WITH TIME ZONE
CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    content TEXT
);